"""
Node 1b: Baseline Manager

Responsibilities:
- If scan_codebase is true, scans the entire C# repository and asks the Roslyn server
  to extract all logical objects, creating a baseline.
- If scan_codebase is false, loads the baseline from the cache folder.
- Populates state["baseline_objects"].
"""

import os
import json
import numpy as np
from src.utils import logger, get_roslyn_server, audit_snapshot

PROJECT_CACHE = {}

def get_project_name(file_path, repo_path):
    dir_name = os.path.dirname(file_path)
    if dir_name in PROJECT_CACHE:
        return PROJECT_CACHE[dir_name]
        
    current_dir = os.path.join(repo_path, dir_name)
    
    while current_dir and len(current_dir) >= len(repo_path):
        if os.path.isdir(current_dir):
            try:
                csprojs = [f for f in os.listdir(current_dir) if f.endswith('.csproj')]
                if csprojs:
                    project = csprojs[0].replace('.csproj', '')
                    PROJECT_CACHE[dir_name] = project
                    return project
            except OSError:
                pass
        parent = os.path.dirname(current_dir)
        if parent == current_dir:
            break
        current_dir = parent
        
    parts = file_path.replace('\\', '/').split('/')
    fallback = parts[0] if parts else "Unknown"
    PROJECT_CACHE[dir_name] = fallback
    return fallback

def _is_excluded(file_path):
    """Simple heuristic to avoid scanning tests and autogenerated code."""
    path_lower = file_path.lower()
    if "\\test\\" in path_lower or "/test/" in path_lower:
        return True
    if "\\tests\\" in path_lower or "/tests/" in path_lower:
        return True
    if path_lower.endswith(".designer.cs"):
        return True
    if "\\obj\\" in path_lower or "/obj/" in path_lower:
        return True
    if "\\bin\\" in path_lower or "/bin/" in path_lower:
        return True
    return False

def node_1b_baseline_manager(state):
    logger.info("=" * 60)
    logger.info("NODE 1b: Baseline Manager")
    logger.info("=" * 60)

    config = state["config"]
    scan_codebase = config.get("scan_codebase", False)
    baseline_cache_folder = config.get("baseline_cache_folder", "cache")
    repo_path = config.get("repo_path", "")
    target_framework = config.get("target_framework", "net10.0")

    os.makedirs(baseline_cache_folder, exist_ok=True)
    cache_file = os.path.join(baseline_cache_folder, "baseline.json")

    baseline_objects = []

    if not scan_codebase:
        logger.info(f"scan_codebase is False. Attempting to load from {cache_file}...")
        if os.path.exists(cache_file):
            with open(cache_file, "r", encoding="utf-8") as f:
                baseline_objects = json.load(f)
            logger.info(f"Loaded {len(baseline_objects)} baseline objects from cache.")
        else:
            logger.warning("Cache file not found! Returning empty baseline.")
    else:
        logger.info(f"scan_codebase is True. Initiating full repository scan at: {repo_path}")
        server = get_roslyn_server(target_framework)
        
        cs_files = []

        blacklist = {"bin", "obj", ".vs", ".git", ".idea", "packages", "node_modules"}

        for root, dirs, files in os.walk(repo_path):
            # Prune crawler directories in-place to avoid descending into ignored branches
            dirs[:] = [d for d in dirs if d.lower() not in blacklist and "backup" not in d.lower()]

            for file in files:
                if file.endswith(".cs"):
                    full_path = os.path.join(root, file)
                    rel_path = os.path.relpath(full_path, repo_path)
                    if not _is_excluded(rel_path):
                        cs_files.append(rel_path)
                        
        logger.info(f"Found {len(cs_files)} C# files to scan (excluding tests/obj/bin).")
        
        for i, rel_path in enumerate(cs_files):
            if i % 100 == 0 and i > 0:
                logger.info(f"  Scanning progress: {i}/{len(cs_files)} files...")
                
            full_path = os.path.join(repo_path, rel_path)
            try:
                with open(full_path, "r", encoding="utf-8-sig") as f:
                    code = f.read()
            except Exception as e:
                logger.error(f"Failed to read file {full_path}: {e}")
                continue
                
            objects = server.baseline_extract(code)
            project = get_project_name(rel_path, repo_path)
            
            for obj in objects:
                baseline_objects.append({
                    "logical_object": obj["signature"],
                    "parent_object": obj["parent_signature"],
                    "project": project,
                    "first_seen_date": None,
                    "last_seen_date": None,
                    "hit_count": 0,
                    "commits": [],
                    "is_dead_code": False,
                    "raw_complexity_score": obj.get("raw_complexity_score", 0),
                    "object_type": obj.get("object_type", "method")
                })
                
        logger.info(f"Extracted {len(baseline_objects)} baseline objects.")
        with open(cache_file, "w", encoding="utf-8") as f:
            json.dump(baseline_objects, f, indent=2)
        logger.info(f"Saved baseline to {cache_file}")

    if config.get("enable_auto_calibration", False):
        target = config.get("complexity_percentile_target", 0.75)
        target_property = config.get("complexity_percentile_target_property", target)
        target_constructor = config.get("complexity_percentile_target_constructor", target)
        
        scores_property = [obj.get("raw_complexity_score", 0) for obj in baseline_objects if obj.get("object_type") == "property"]
        scores_constructor = [obj.get("raw_complexity_score", 0) for obj in baseline_objects if obj.get("object_type") == "constructor"]
        scores_method = [obj.get("raw_complexity_score", 0) for obj in baseline_objects if obj.get("object_type") == "method"]
        
        if scores_property:
            config["max_property_threshold"] = float(np.percentile(scores_property, target_property * 100))
        else:
            config["max_property_threshold"] = 17.0
            
        if scores_constructor:
            config["max_constructor_threshold"] = float(np.percentile(scores_constructor, target_constructor * 100))
        else:
            config["max_constructor_threshold"] = 17.0
            
        if scores_method:
            config["max_method_threshold"] = float(np.percentile(scores_method, target * 100))
        else:
            config["max_method_threshold"] = 17.0
            
        logger.info(f"Auto-Calibration thresholds: Property={config['max_property_threshold']:.2f}, "
                    f"Constructor={config['max_constructor_threshold']:.2f}, "
                    f"Method={config['max_method_threshold']:.2f}")

    logger.info("Node 1b Finished.")
    output_state = {"baseline_objects": baseline_objects, "config": config}
    audit_snapshot({
        "auto_calibration_thresholds": {
            "max_property_threshold": config.get("max_property_threshold"),
            "max_constructor_threshold": config.get("max_constructor_threshold"),
            "max_method_threshold": config.get("max_method_threshold")
        },
        "total_baseline_objects": len(baseline_objects)
    }, "node_1b_baseline_manager", "Baseline and Calibration Summary", config)
    return output_state
